services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autograder
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main_network
  redis:
        container_name: redis
        image: redis:latest
        expose:
            - "6379"
        networks:
            - main_network
  autograder:
      container_name: autograder
      image: autograder
      build:
        context: autograder2/
        dockerfile: dev/Dockerfile
      entrypoint:
        [
          "/bin/bash",
          "-c",
          "git config --global --add safe.directory /home/tjctgrader/autograder2 && \
          git config --global --add safe.directory /home/tjctgrader && \
          cd dev && \
          /bin/bash entrypoint.sh"
        ]
      ports:
          - "3000:3000"
      networks:
          - main_network
      volumes:
          - ./autograder2/:/home/tjctgrader/autograder2
          - ./.git:/home/tjctgrader/.git
          - /home/tjctgrader/autograder2/.ruff_cache
      depends_on:
        - postgres
        - coderunner
  coderunner:
    build:
      context: coderunner/
      dockerfile: ./dev/Dockerfile
    container_name: coderunner
    restart: unless-stopped
    volumes:
      - ./coderunner:/home/tjctgrader/coderunner
      - /home/tjctgrader/coderunner/nsjail
      - /home/tjctgrader/coderunner/target
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - PROD=false
    networks:
      - main_network
    privileged: true
  celery:
        container_name: celery
        image: autograder
        networks:
            - main_network
        entrypoint:
            [
                "/bin/sh",
                "-c",
                "git config --global --add safe.directory /home/tjctgrader/autograder2 && \
                git config --global --add safe.directory /home/tjctgrader && \
                uv run celery --app autograder worker -l INFO -Ofair"
            ]
        depends_on:
            - autograder
            - redis
        volumes:
          - ./autograder2/:/home/tjctgrader/autograder2
          - ./.git:/home/tjctgrader/.git
          - /home/tjctgrader/autograder2/.ruff_cache
  celery_coderunner:
        container_name: celery_coderunner
        image: autograder
        networks:
            - main_network
        entrypoint:
            [
                "/bin/sh",
                "-c",
                "git config --global --add safe.directory /home/tjctgrader/autograder2 && \
                git config --global --add safe.directory /home/tjctgrader && \
                uv run celery --app autograder worker -l INFO -Q coderunner_queue -c 2"
            ]
        depends_on:
            - autograder
            - redis
        volumes:
          - ./autograder2/:/home/tjctgrader/autograder2
          - ./.git:/home/tjctgrader/.git
          - /home/tjctgrader/autograder2/.ruff_cache
  frontend:
        container_name: frontend
        build:
          context: ./autograder2/frontend
          dockerfile: Dockerfile
        ports:
          - "5173:5173"
        networks:
          - main_network
        depends_on:
          - autograder
        environment:
          - NODE_ENV=development
    
 
      

volumes:
  pgdata:
    name: autograder-pgdata

networks:
  main_network:
    driver: bridge